name: Publish

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'
      - 'v[0-9]+\.[0-9]+\.[0-9]+-[a-z]+'
      - 'v[0-9]+\.[0-9]+\.[0-9]+-[a-z]+\.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 21
      - name: Fix borked permissions
        run: chmod +x ./gradlew
      - name: Setup Gradle and Validate Wrapper
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
      - name: Run gradle tasks
        run: ./gradlew build publish
        env:
          NANITE_DEPLOY: ${{ secrets.NANITE_DEPLOY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
